language: node_js
node_js: "6"
script: npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: simple-storefront
  region: us-east-1
  skip_cleanup: true
  local-dir: public
  detect_encoding: true
  acl: public_read
notifications:
  email:
    on_failure: true
cache:
  directories:
    - node_modules
